# Site settings
source:         jekyll-source

title:          Design Resource Base
description:    IMS Health
permalink:      pretty
markdown:       kramdown
highlighter:    rouge
exclude:        ['node_modules', 'dist', 'gulpfile.js', 'package.json', '.gitignore']

kramdown:
  auto_ids:     true